version: '3.1'

services:

  db:
    image: mysql:8
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: greendog
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
      MYSQL_PASSWORD: root

  adminer:
      image: adminer
      ports:
        - "8000:8080"